-
    title: Catégorie principale
    slug: category1

-
    title: Catégorie principale 2
    slug: category2

-
    title: Catégorie secondaire
    slug: category3
    parent_category_slug: category2
